[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.36.25",
    "botocore>=1.36.25",
    "requests>=2.32.3",
]
